---
description: "#{repo}"
builds:
- platform: "alpine"
  arch: "amd64"
  asset_filename: "monitoring-plugins-alpine_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'alpine'"
  - "entity.system.arch == 'amd64'"

- platform: "amazon"
  arch: "amd64"
  asset_filename: "monitoring-plugins-amazon_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'amazon'"
  - "entity.system.arch == 'amd64'"

- platform: "centos6"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos6_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '6'"
  - "entity.system.arch == 'amd64'"

- platform: "centos7"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos7_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '7'"
  - "entity.system.arch == 'amd64'"

- platform: "debian"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.arch == 'amd64'"
