language: c
compiler:
- clang
- gcc
services:
- docker
script:
- travis-build.sh
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git
  bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-disk-checks
  cleanup: false 
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: jZIippZkdDlTLXTohWa/FTZQ/k16dfzefitCpXJpe6UxbWVF0zQrl1kfweZTh+jAQNXZoUZMAIiAYjMB0G9QZWVS2vtrl9sH53yiUC8q+R4DypTUpkOU54p1xxfyKTF4k9jzogKqjlIkH6n91XwlZsqfj1/dL0PKstfNXeGpqWWP1dCRhZftt8WWPdSTXASn0XqPWMqTEOey48CggZxWDUsqzYGjwvdgy5ZSjGTVH/SqsTNTksGV6QOaZ3WPk/PPr2sHBVSfOe9K3jPcau1P6zy17fvpwZxyTKR1ExrTjiB6WFE+cAMGs6vj5XMD3ZcWVn0nvaE3/WTjY4wn0tbvfQHzBQTMfi8dz4Fndc/gq2ioLswASQyqPmwcGva/GJ4M+R2hcREmTqhmwuRhK4gx+7vVD4WYsR7xNuD/vtOlDQpZnPxwSF9hvhYmlGMUC0vzPWuCChi/kM9tVDvtTH66W96A/lqyNUQbLIcLpyBb7jGUCckqGmJnrsuBuN+dG9Aj16cyElPKYXDGpk05zLzAVf0IVS05mAL3MplLgKDfymhmET9s6h9D1lu8KjYA8EWDwdIZH5YAspJIfbSc9cbcHrzVcuvFu1bks178Eck6vN9Cz8A65Zu/Aw4OjNoUBI/OPxpdZlAL4+MUe/7jCSn5ZnlH9ulehzWOzeZdf0VSlxI=
