name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: mkdir dist || echo "${TRAVIS_REPO_SLUG}-${TRAVIS_TAG}" > dist/test.txt
      env:
          TRAVIS_REPO_SLUG: ${{github.repository}}
          TRAVIS_TAG: ${{github.ref_name}}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ github.ref_name }}
        overwrite: true
        file_glob: true

